<?php

/**
 * @file
 * Collects votes on different topics in the form of multiple choice questions.
 */

use Symfony\Component\HttpFoundation\Request;
use Drupal\field\Field;

/**
 * Denotes that the poll is not published.
 */
const POLL_NOT_PUBLISHED = 0;

/**
 * Denotes that the poll is published.
 */
const POLL_PUBLISHED = 1;

/**
 * Implements hook_help().
 */
function poll_help($path, $arg) {
  switch ($path) {
    case 'admin/help#poll':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Poll module can be used to create simple surveys or questionnaires that display cumulative results. A poll is a good way to receive feedback from site users and community members. For more information, see the online handbook entry for the <a href="@poll">Poll module</a>.', array('@poll' => 'http://drupal.org/documentation/modules/poll/')) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Creating a poll') . '</dt>';
      $output .= '<dd>' . t('Users can create a poll by clicking on Poll on the <a href="@add-content">Add new content</a> page, and entering the question being posed, the answer choices, and beginning vote counts for each choice. The status (closed or active) and duration (length of time the poll remains active for new votes) can also be specified.', array('@add-content' => url('node/add'))) . '</dd>';
      $output .= '<dt>' . t('Viewing polls') . '</dt>';
      $output .= '<dd>' . t('You can visit the <a href="@poll">Polls</a> page to view all current polls, or alternately enable the <em>Most recent poll</em> Block on the <a href="@blocks">Blocks administration page</a>. To vote in or view the results of a specific poll, you can click on the poll itself.', array(
          '@poll' => url('poll'),
          '@blocks' => url('admin/structure/Block')
        )) . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}


/**
 * Implements hook_menu().
 */
function poll_menu() {
  $items['admin/structure/poll'] = array(
    'title' => 'Polls',
    'description' => 'Manage Polls for your site.',
    'route_name' => 'poll_list',
  );

  $items['poll/add'] = array(
    'route_name' => 'poll_add',
    'type' => MENU_LOCAL_ACTION,
  );

  $items['poll/%poll/edit'] = array(
    'title' => 'Edit',
    'route_name' => 'poll_edit',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  $items['poll/%poll'] = array(
    'route_name' => 'poll_view',
    'type' => MENU_LOCAL_ACTION,
  );

  return $items;
}

/**
 * Entity URI callback.
 */
function poll_uri($poll) {
  return array(
    'path' => 'poll/' . $poll->id(),
  );
}

/**
 * Create choice field for the poll entity.
 */
function poll_install_choice_field() {
  $poll_choice_field = Field::fieldInfo()->getField('poll', 'field_choice');
  if (empty($poll_choice_field)) {
    $field = array(
      'name' => 'field_choice',
      'entity_type' => 'poll',
      'module' => 'poll',
      'type' => 'poll_choice',
      'cardinality' => '-1',
      'locked' => FALSE,
    );
    entity_create('field_entity', $field)->save();

    $instance = array(
      'field_name' => 'field_choice',
      'entity_type' => 'poll',
      'label' => 'Choice',
      'bundle' => 'poll',
      'description' => t('Enter a poll choice and default vote.'),
      'required' => FALSE,
      'settings' => array(
        'max_length' => 255,
      ),
    );
    entity_create('field_instance', $instance)->save();

    // Assign form display settings for the 'default' view mode.
    entity_get_form_display('poll', 'poll', 'default')
      ->setComponent('field_choice', array(
        'type' => 'poll_choice_default',
        'settings' => array(
          'size' => '60',
          'placeholder' => '',
        ),
        'weight' => 0,
      ))
      ->save();

    entity_get_display('poll', 'poll', 'default')
      ->setComponent('field_choice', array(
        'label' => 'Choice',
        'type' => 'poll_choice_default',
        'settings' => array(),
      ))
      ->save();
  }
}


/**
 * Implements hook_admin_paths().
 */
function poll_admin_paths() {
  if (Drupal::config('node.settings')->get('use_admin_theme')) {
    $paths = array(
      'poll/*/edit' => TRUE,
      'poll/*/delete' => TRUE,
      'poll/*/revisions' => TRUE,
      'poll/*/revisions/*/revert' => TRUE,
      'poll/*/revisions/*/delete' => TRUE,
      'poll/*/translations' => TRUE,
      'poll/*/translations/*' => TRUE,
      'poll/add' => TRUE,
      'poll/add/*' => TRUE,
    );
    return $paths;
  }
}

/**
 * Implements hook_theme().
 */
function poll_theme() {
  $theme_hooks = array(
    'poll_vote' => array(
      'template' => 'poll-vote',
      'render element' => 'form',
    ),
    'poll_choices' => array(
      'render element' => 'form',
    ),
    'poll_results' => array(
      'template' => 'poll-results',
      'variables' => array('raw_title' => NULL, 'results' => NULL, 'votes' => NULL, 'raw_links' => NULL, 'block' => NULL, 'nid' => NULL, 'vote' => NULL),
    ),
    'poll_meter' => array(
      'variables' => array('display_value' => NULL, 'form' => NULL, 'high' => NULL, 'low' => NULL, 'max' => NULL, 'min' => NULL, 'optimum' => NULL, 'value' => NULL, 'percentage' => NULL, 'attributes' => array()),
      'template' => 'meter',
    ),
  );

  return $theme_hooks;
}


/**
 * Implements template_preprocess_HOOK() for poll-vote.tpl.php.
 */
function template_preprocess_poll_vote(&$variables) {
  $form = $variables['form'];

//  unset($form['#node']);
  //unset($form['#validate']);
  //unset($form['#submit']);

//  $data = $form;
//$data = drupal_render($form['choice']);
//  $string = check_plain(print_r($data, TRUE));
//  $string = '<pre>' . $string . '</pre>';
//  trigger_error($string);

  $variables['title'] = check_plain($form['#node']->title);
  $variables['choice'] = drupal_render($form['choice']);
  $variables['vote'] = drupal_render($form['submit']);
  $variables['rest'] = drupal_render_children($form);

//  $variables['block'] = $form['#block'];
//  if ($variables['block']) {
//    $variables['theme_hook_suggestions'][] = 'poll_vote__block';
//  }

}


///**
// * Implements hook_theme().
// */
//function link_theme() {
//  return array(
//    'link_formatter_link_separate' => array(
//      'variables' => array('title' => NULL, 'url_title' => NULL, 'href' => NULL, 'options' => array()),
//      'template' => 'link-formatter-link-separate',
//    ),
//  );
//}
//
///**
// * Prepares variables for separated link field templates.
// *
// * This template outputs a separate title and link.
// *
// * Default template: link-formatter-link-separate.html.twig.
// *
// * @param array $variables
// *   An associative array containing:
// *   - title: (optional) A descriptive or alternate title for the link, which
// *     may be different than the actual link text.
// *   - url_title: The anchor text for the link.
// *   - href: The link URL.
// *   - options: (optional) An array of options to pass to l().
// */
//function template_preprocess_link_formatter_link_separate(&$variables) {
//  if (!empty($variables['title'])) {
//    $variables['title'] = check_plain($variables['title']);
//  }
//  $variables['link'] = l($variables['url_title'], $variables['href'], $variables['options']);
//}
