<?php

/**
 * @file
 *
 */

/**
 * Implements hook_help().
 */
function choice_help($path, $arg) {
  switch ($path) {
    case 'admin/help#choice':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The choice module allows you to create fields that contain choices and initial values for each. See the <a href="!field">Field module help</a> and the <a href="!field_ui">Field UI help</a> pages for general information on fields and how to create and manage them. For more information, see the <a href="!choice_documentation">online documentation for the Telephone module</a>.', array('!field' => \Drupal::url('help.page', array('name' => 'field')), '!field_ui' => \Drupal::url('help.page', array('name' => 'field_ui')), '!choice_documentation' => 'https://drupal.org/documentation/modules/choice')) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Managing and displaying choice fields') . '</dt>';
      $output .= '<dd>todo ...</dd>';
      $output .= '</dl>';
      return $output;
  }
}
